name: run scraper.py

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install chromedriver
        uses: browser-actions/setup-chrome@v1
      
      - name: execute scraper script
        run: python scraper.py
      
      - name: send email
        env:
          EMAIL: ${{secrets.EMAIL}}
          EMAIL_PASSKEY: ${{secrets.EMAIL_PASSKEY}}
        run: python send_email.py